app.docker.host=10.10.10.224

spring.application.name=nosql-crud
spring.mongodb.uri=mongodb://admin:adminpass@${app.docker.host}:27017/admin
spring.jackson.time-zone=America/Toronto

# Redis cache configuration
spring.data.redis.host=${app.docker.host}
spring.data.redis.port=6379
spring.data.redis.password=redispass